# SPDX-License-Identifier: GPL-2.0
#
# asm headers that all architectures except um should have
# (This file is not included when SRCARCH=um since UML borrows several
# asm headers from the host architecutre.)

mandatory-y += dma-contiguous.h
mandatory-y += kmap_size.h
mandatory-y += module.lds.h
mandatory-y += msi.h
mandatory-y += simd.h
